---
- hosts: all
  tasks:
    - name: "Create loopback 185"
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback185
        state: purged

    - name: "List interfaces"
      cisco.ios.ios_command:
        commands: show ip interface brief
      register: output

      
    - name: "Print output"
      debug:
        msg: "{{ output.stdout_lines.0 }}"#